In [1]:
## overfitting:train the model with more attributes that is called overfitting problem.If model overfit then high error less accuracy
##             low bias high variance
##             low training score high test score

## underfitting:train the model with less attribute is called underfitting.If model underfit then high error less accuracy
##             high bias low variance
##             high training score low test score
## bestfit:train the model with relevant attribute(neither overfit nor underfit)
##             low bias low variance

In [2]:
# what is the technique to reduce underfit
#             by adding more relevant attribute
# what is the technique to reduce overfitting problem
#             we have few technique to remove the irrelevant attribute
#             1)regularization technique
#             2)cross validation
#             3)pcs(principal component analysis)
#             4)drop out the neuron(deep learning)
#             5)ensemble technique

# Reguralization technique
## regularize the coefficient of independent variable

## 1)Ridge regression=l2
###   scale down/reduce high coef to low coef
## 2)lasso regression=l1
###    scale down high coef to zero and low coef
## 3)elasticnet=l1+l2

# How to remove the attribute
## 1)RFE(recursive feature elimination)
## 2)lasso regression
## 3)principal component

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score

In [4]:
data=pd.read_csv(r'C:\nit\38_regularization\car-mpg.csv')
data

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,1,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,1,chevy s-10

In [5]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [6]:
data=data.drop(['car_name'],axis=1)
data['origin']=data['origin'].replace({1:'america',2:'europe',3:'asia'})
data=pd.get_dummies(data,columns=['origin'],dtype=int)
data=data.replace('?',np.nan)

In [7]:
data

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140,3449,10.5,70,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,1,0,0
394,44.0,4,97.0,52,2130,24.6,82,1,0,0,1
395,32.0,4,135.0,84,2295,11.6,82,1,1,0,0
396,28.0,4,120.0,79,2625,18.6,82,1,1,0,0
397,31.0,4,119.0,82,2720,19.4,82,1,1,0,0

In [8]:
data=data.apply(pd.to_numeric,errors='ignore')
numeric_cols=data.select_dtypes(include=[np.number]).columns
data[numeric_cols]=data[numeric_cols].apply(lambda x:x.fillna(x.median()))

C:\Users\91995\AppData\Local\Temp\ipykernel_21336\3959228371.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data=data.apply(pd.to_numeric,errors='ignore')

In [9]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140.0,3449,10.5,70,0,1,0,0

In [10]:
x=data.drop(['mpg'],axis=1) #dependent variable
y=data[['mpg']] #independent variable

In [11]:
# scaling the data
x_s=preprocessing.scale(x)
x_s=pd.DataFrame(x_s,columns=x.columns)

y_s=preprocessing.scale(y)
y_s=pd.DataFrame(y_s,columns=y.columns)

In [12]:
x_s

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,1.498191,1.090604,0.673118,0.630870,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
1,1.498191,1.503514,1.589958,0.854333,-1.477038,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
2,1.498191,1.196232,1.197027,0.550470,-1.658577,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
3,1.498191,1.061796,1.197027,0.546923,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
4,1.498191,1.042591,0.935072,0.565841,-1.840117,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
...,...,...,...,...,...,...,...,...,...,...
393,-0.856321,-0.513026,-0.479482,-0.213324,0.011586,1.621983,0.941412,0.773559,-0.497643,-0.461968
394,-0.856321,-0.925936,-1.370127,-0.993671,3.279296,1.621983,0.941412,-1.292726,-0.497643,2.164651
395,-0.856321,-0.561039,-0.531873,-0.798585,-1.440730,1.621983,0.941412,0.773559,-0.497643,-0.461968
396,-0.856321,-0.705077,-0.662850,-0.408411,1.100822,1.621983,0.941412,0.773559,-0.497643,-0.461968
397,-0.856321,-0.714680,-0.584264,-0.296088,1.391285,1.621983,0.941412,0.773559,-0.497643,-0.461968

In [13]:
data.shape

(398, 11)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x_s,y_s,test_size=0.20,random_state=0)

In [15]:
x_train.shape

(318, 10)

In [16]:
regression_model=LinearRegression()
regression_model.fit(x_train,y_train)

for idx,col_name in enumerate(x_train.columns):
    print('The coefficient for {} is {}'.format(col_name,regression_model.coef_[0][idx]))
intercept=regression_model.intercept_[0]
print('The intercept is {}'.format(intercept))

The coefficient for cyl is 0.24638776053571776
The coefficient for disp is 0.29177092098664337
The coefficient for hp is -0.18081621820393634
The coefficient for wt is -0.6675530609868122
The coefficient for acc is 0.06537309205777068
The coefficient for yr is 0.34817702594267175
The coefficient for car_type is 0.3339231253960363
The coefficient for origin_america is -0.08117984631927014
The coefficient for origin_asia is 0.06986098209664954
The coefficient for origin_europe is 0.03000316124228805
The intercept is -0.01800683137092325

In [18]:
ridge_model=Ridge(alpha=0.4)
ridge_model.fit(x_train,y_train)
print('Ridge model coef:{}'.format(ridge_model.coef_))

Ridge model coef:[ 0.24242411  0.28008024 -0.18071842 -0.65711583  0.06353256  0.34721777
  0.32998816 -0.08077573  0.06989674  0.02945199]

In [19]:
lasso_model=Lasso(alpha=0.1)
lasso_model.fit(x_train,y_train)
print('Lasso model coef:{}'.format(lasso_model.coef_))

Lasso model coef:[-0.         -0.         -0.07247557 -0.45867691  0.          0.2698134
  0.11341188 -0.04988145  0.          0.        ]